"""initial schema

Revision ID: 11ffefe568a1
Revises: 
Create Date: 2026-09-03 13:23:27.959718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11ffefe568a1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('espn_event_id', sa.String(length=16), nullable=True),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('phase', sa.String(length=4), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('home_team', sa.String(length=4), nullable=False),
    sa.Column('away_team', sa.String(length=4), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('kickoff', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_event_id')
    )
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_games_away_team'), ['away_team'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_home_team'), ['home_team'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_phase'), ['phase'], unique=False)
        batch_op.create_index(batch_op.f('ix_games_season'), ['season'], unique=False)

    op.create_table('players',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('espn_id', sa.String(length=12), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('team', sa.String(length=4), nullable=True),
    sa.Column('headshot', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_players_espn_id'), ['espn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_players_team'), ['team'], unique=False)

    op.create_table('snap_counts',
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('player_name', sa.String(length=64), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('opponent', sa.String(length=4), nullable=True),
    sa.Column('offense_snaps', sa.Integer(), nullable=False),
    sa.Column('offense_pct', sa.Float(), nullable=False),
    sa.Column('defense_snaps', sa.Integer(), nullable=False),
    sa.Column('defense_pct', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('game_id', 'player_name', 'team')
    )
    with op.batch_alter_table('snap_counts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_snap_counts_season'), ['season'], unique=False)

    op.create_table('sync_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=12), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=8), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.create_index('ix_sync_log_status_id', ['status', 'id'], unique=False)

    op.create_table('teams',
    sa.Column('abbr', sa.String(length=4), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('conference', sa.String(length=4), nullable=True),
    sa.Column('division', sa.String(length=16), nullable=True),
    sa.Column('color', sa.String(length=9), nullable=True),
    sa.Column('color2', sa.String(length=9), nullable=True),
    sa.Column('logo', sa.String(length=512), nullable=True),
    sa.Column('espn_id', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('abbr')
    )
    op.create_table('player_game_stats',
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('player_id', sa.String(length=24), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('pass_att', sa.Integer(), nullable=False),
    sa.Column('pass_cmp', sa.Integer(), nullable=False),
    sa.Column('pass_yds', sa.Integer(), nullable=False),
    sa.Column('pass_td', sa.Integer(), nullable=False),
    sa.Column('pass_int', sa.Integer(), nullable=False),
    sa.Column('sacks_taken', sa.Integer(), nullable=False),
    sa.Column('rush_att', sa.Integer(), nullable=False),
    sa.Column('rush_yds', sa.Integer(), nullable=False),
    sa.Column('rush_td', sa.Integer(), nullable=False),
    sa.Column('rush_long', sa.Integer(), nullable=False),
    sa.Column('targets', sa.Integer(), nullable=False),
    sa.Column('receptions', sa.Integer(), nullable=False),
    sa.Column('rec_yds', sa.Integer(), nullable=False),
    sa.Column('rec_td', sa.Integer(), nullable=False),
    sa.Column('rec_long', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'player_id')
    )
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_game_stats_team'), ['team'], unique=False)

    op.create_table('plays',
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('play_id', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('clock', sa.String(length=8), nullable=True),
    sa.Column('down', sa.Integer(), nullable=True),
    sa.Column('ydstogo', sa.Integer(), nullable=True),
    sa.Column('yardline_100', sa.Integer(), nullable=True),
    sa.Column('posteam', sa.String(length=4), nullable=True),
    sa.Column('defteam', sa.String(length=4), nullable=True),
    sa.Column('play_type', sa.String(length=16), nullable=True),
    sa.Column('yards_gained', sa.Float(), nullable=True),
    sa.Column('air_yards', sa.Float(), nullable=True),
    sa.Column('yac', sa.Float(), nullable=True),
    sa.Column('pass_location', sa.String(length=8), nullable=True),
    sa.Column('pass_depth', sa.String(length=8), nullable=True),
    sa.Column('run_gap', sa.String(length=8), nullable=True),
    sa.Column('run_location', sa.String(length=8), nullable=True),
    sa.Column('passer_id', sa.String(length=24), nullable=True),
    sa.Column('rusher_id', sa.String(length=24), nullable=True),
    sa.Column('receiver_id', sa.String(length=24), nullable=True),
    sa.Column('complete_pass', sa.Boolean(), nullable=True),
    sa.Column('touchdown', sa.Boolean(), nullable=False),
    sa.Column('interception', sa.Boolean(), nullable=False),
    sa.Column('sack', sa.Boolean(), nullable=False),
    sa.Column('epa', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('offense_players', sa.Text(), nullable=True),
    sa.Column('defense_players', sa.Text(), nullable=True),
    sa.Column('n_pass_rushers', sa.Integer(), nullable=True),
    sa.Column('is_blitz', sa.Boolean(), nullable=True),
    sa.Column('desc', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('game_id', 'play_id')
    )
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plays_defteam'), ['defteam'], unique=False)
        batch_op.create_index('ix_plays_game_quarter', ['game_id', 'quarter'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_passer_id'), ['passer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_posteam'), ['posteam'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_plays_rusher_id'), ['rusher_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plays_rusher_id'))
        batch_op.drop_index(batch_op.f('ix_plays_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_plays_posteam'))
        batch_op.drop_index(batch_op.f('ix_plays_passer_id'))
        batch_op.drop_index('ix_plays_game_quarter')
        batch_op.drop_index(batch_op.f('ix_plays_defteam'))

    op.drop_table('plays')
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_game_stats_team'))

    op.drop_table('player_game_stats')
    op.drop_table('teams')
    with op.batch_alter_table('sync_log', schema=None) as batch_op:
        batch_op.drop_index('ix_sync_log_status_id')

    op.drop_table('sync_log')
    with op.batch_alter_table('snap_counts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_snap_counts_season'))

    op.drop_table('snap_counts')
    with op.batch_alter_table('players', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_players_team'))
        batch_op.drop_index(batch_op.f('ix_players_name'))
        batch_op.drop_index(batch_op.f('ix_players_espn_id'))

    op.drop_table('players')
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_games_season'))
        batch_op.drop_index(batch_op.f('ix_games_phase'))
        batch_op.drop_index(batch_op.f('ix_games_home_team'))
        batch_op.drop_index(batch_op.f('ix_games_away_team'))

    op.drop_table('games')
    # ### end Alembic commands ###
