"""coaching feature: play-call columns, coaching staff, depth charts, PFR advanced

Revision ID: ca632fe3c06a
Revises: 11ffefe568a1
Create Date: 2026-09-09 15:51:08.620524

One revision covering the whole coaching data layer:

  * 41 columns onto `plays` (play-call context from load_pbp, personnel and
    coverage from load_participation, FTN charting flags) and 9 defensive
    columns onto `player_game_stats`. All nullable with no server default --
    they are genuinely unknown for existing rows, and backfilling a 0 or a
    False would be indistinguishable from a charted value.
  * new tables `coaches`, `coaching_staff`, `depth_chart`,
    `player_season_advanced`.

Adding 41 nullable columns to `plays` is metadata-only on Postgres 11+ (no
table rewrite), so this is fast even against a populated table. On SQLite
render_as_batch rewrites the table, which is fine at local-development sizes.

Downgrade drops the new columns and tables, and therefore the data in them;
it is safe in the sense that nothing predating this revision is touched.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca632fe3c06a'
down_revision: Union[str, Sequence[str], None] = '11ffefe568a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coaches',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('depth_chart',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=8), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('formation', sa.String(length=16), nullable=False),
    sa.Column('depth_position', sa.String(length=8), nullable=False),
    sa.Column('player_id', sa.String(length=24), nullable=False),
    sa.Column('depth_team', sa.Integer(), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('player_name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('season', 'week', 'game_type', 'team', 'formation', 'depth_position', 'player_id')
    )
    with op.batch_alter_table('depth_chart', schema=None) as batch_op:
        batch_op.create_index('ix_depth_chart_player', ['player_id'], unique=False)
        batch_op.create_index('ix_depth_chart_season_team', ['season', 'team'], unique=False)

    op.create_table('player_season_advanced',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('pfr_id', sa.String(length=16), nullable=False),
    sa.Column('player_id', sa.String(length=24), nullable=True),
    sa.Column('player_name', sa.String(length=128), nullable=True),
    sa.Column('team', sa.String(length=4), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('games', sa.Integer(), nullable=True),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('prss', sa.Float(), nullable=True),
    sa.Column('hrry', sa.Float(), nullable=True),
    sa.Column('qbkd', sa.Float(), nullable=True),
    sa.Column('bltz', sa.Float(), nullable=True),
    sa.Column('sk', sa.Float(), nullable=True),
    sa.Column('tgt', sa.Float(), nullable=True),
    sa.Column('cmp_percent', sa.Float(), nullable=True),
    sa.Column('rat', sa.Float(), nullable=True),
    sa.Column('dadot', sa.Float(), nullable=True),
    sa.Column('comb', sa.Float(), nullable=True),
    sa.Column('m_tkl_percent', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('season', 'pfr_id')
    )
    with op.batch_alter_table('player_season_advanced', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_season_advanced_player_id'), ['player_id'], unique=False)

    op.create_table('coaching_staff',
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('head_coach_id', sa.String(length=48), nullable=True),
    sa.Column('oc_id', sa.String(length=48), nullable=True),
    sa.Column('dc_id', sa.String(length=48), nullable=True),
    sa.Column('offensive_play_caller_id', sa.String(length=48), nullable=True),
    sa.Column('defensive_play_caller_id', sa.String(length=48), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['dc_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['defensive_play_caller_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['head_coach_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['oc_id'], ['coaches.id'], ),
    sa.ForeignKeyConstraint(['offensive_play_caller_id'], ['coaches.id'], ),
    sa.PrimaryKeyConstraint('season', 'team')
    )
    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('def_tackles_solo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('def_tackle_assists', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('def_tackles_for_loss', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('def_fumbles_forced', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('def_sacks', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('def_qb_hits', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('def_interceptions', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('def_pass_defended', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('def_tds', sa.Integer(), nullable=True))

    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shotgun', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('no_huddle', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('qb_dropback', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('qb_scramble', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('goal_to_go', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('first_down', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('penalty', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('pass_length', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('drive', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fixed_drive', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fixed_drive_result', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('drive_start_yard_line', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('drive_play_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('series', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('series_result', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('score_differential', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('game_seconds_remaining', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('half_seconds_remaining', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('posteam_timeouts_remaining', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('xpass', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pass_oe', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('offense_formation', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('offense_personnel', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('defense_personnel', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('defenders_in_box', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('was_pressure', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('defense_man_zone_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('defense_coverage_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('route', sa.String(length=24), nullable=True))
        batch_op.add_column(sa.Column('time_to_throw', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('n_offense', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('n_defense', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_play_action', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_motion', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_screen_pass', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_rpo', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_trick_play', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('is_qb_sneak', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('qb_location', sa.String(length=2), nullable=True))
        batch_op.add_column(sa.Column('n_offense_backfield', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('n_defense_box', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plays', schema=None) as batch_op:
        batch_op.drop_column('n_defense_box')
        batch_op.drop_column('n_offense_backfield')
        batch_op.drop_column('qb_location')
        batch_op.drop_column('is_qb_sneak')
        batch_op.drop_column('is_trick_play')
        batch_op.drop_column('is_rpo')
        batch_op.drop_column('is_screen_pass')
        batch_op.drop_column('is_motion')
        batch_op.drop_column('is_play_action')
        batch_op.drop_column('n_defense')
        batch_op.drop_column('n_offense')
        batch_op.drop_column('time_to_throw')
        batch_op.drop_column('route')
        batch_op.drop_column('defense_coverage_type')
        batch_op.drop_column('defense_man_zone_type')
        batch_op.drop_column('was_pressure')
        batch_op.drop_column('defenders_in_box')
        batch_op.drop_column('defense_personnel')
        batch_op.drop_column('offense_personnel')
        batch_op.drop_column('offense_formation')
        batch_op.drop_column('pass_oe')
        batch_op.drop_column('xpass')
        batch_op.drop_column('wp')
        batch_op.drop_column('posteam_timeouts_remaining')
        batch_op.drop_column('half_seconds_remaining')
        batch_op.drop_column('game_seconds_remaining')
        batch_op.drop_column('score_differential')
        batch_op.drop_column('series_result')
        batch_op.drop_column('series')
        batch_op.drop_column('drive_play_count')
        batch_op.drop_column('drive_start_yard_line')
        batch_op.drop_column('fixed_drive_result')
        batch_op.drop_column('fixed_drive')
        batch_op.drop_column('drive')
        batch_op.drop_column('pass_length')
        batch_op.drop_column('penalty')
        batch_op.drop_column('first_down')
        batch_op.drop_column('goal_to_go')
        batch_op.drop_column('qb_scramble')
        batch_op.drop_column('qb_dropback')
        batch_op.drop_column('no_huddle')
        batch_op.drop_column('shotgun')

    with op.batch_alter_table('player_game_stats', schema=None) as batch_op:
        batch_op.drop_column('def_tds')
        batch_op.drop_column('def_pass_defended')
        batch_op.drop_column('def_interceptions')
        batch_op.drop_column('def_qb_hits')
        batch_op.drop_column('def_sacks')
        batch_op.drop_column('def_fumbles_forced')
        batch_op.drop_column('def_tackles_for_loss')
        batch_op.drop_column('def_tackle_assists')
        batch_op.drop_column('def_tackles_solo')

    op.drop_table('coaching_staff')
    with op.batch_alter_table('player_season_advanced', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_season_advanced_player_id'))

    op.drop_table('player_season_advanced')
    with op.batch_alter_table('depth_chart', schema=None) as batch_op:
        batch_op.drop_index('ix_depth_chart_season_team')
        batch_op.drop_index('ix_depth_chart_player')

    op.drop_table('depth_chart')
    op.drop_table('coaches')
    # ### end Alembic commands ###
